### ISSUE TITLE
怎样把这个RPN程序融入现有的faster rcnn框架中去呢

### ISSUE THREAD

**Issue by wait1988** [wangshankun/rcnn-optimize#1]

**Comment by wangshankun** [comment]
@wait1988  这个只是rpn的demo，里面的参数和测试使用数据是固定的，我没有把它放回caffe的框架里面，如果要放回caffe，最好新建一个layer，forward函数用这个demo中的rpn逻辑就好了。

ps:这里没有实现anchor的生成，因为每个模型的anchor固定不变，所有就没用代码去做了

**Comment by wangshankun** [comment]
实现了一个直接对接caffe格式的rpn
https://github.com/wangshankun/rcnn-optimize/tree/master/rpn_optimize
